---
apiVersion: v1                    
kind: Namespace
metadata:
  name: pacman-app
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: pacman
  namespace: pacman-app
  labels:
    app.kubernetes.io/name: pacman
  annotations:
    apps.open-cluster-management.io/github-path: deploy
spec:
  type: GitHub
  pathname: https://github.com/liyong-li/k8s-pacman-app.git
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: pacman
  namespace: pacman-app
  annotations: {}
  selfLink: /apis/app.k8s.io/v1beta1/namespaces/pacman-app/applications/pacman
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - pacman
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: pacman-subscription-1
  namespace: pacman-app
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: deploy
  labels:
    app: pacman
  selfLink: /apis/apps.open-cluster-management.io/v1/namespaces/pacman-app/subscriptions/pacman-subscription-1
spec:
  channel: pacman-app/pacman
  placement:
    placementRef:
      name: pacman-placement-1
      kind: PlacementRule
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: pacman-placement-1
  namespace: pacman-app
  labels:
    app: pacman
  selfLink: /apis/apps.open-cluster-management.io/v1/namespaces/pacman-app/placementrules/pacman-placement-1
spec:
  clusterSelector:
    matchLabels:
      app.kubernetes.io/name: pacman

